from qfluentwidgets import SettingCard

from .service import trackerService


class WebTrackerCard(SettingCard):
    def __init__(self, parent=None):
        super().__init__(parent)

    def _initLayout(self): ...
    def _bind(self): ...

    def refreshContent(self): ...
    def _onManageClicked(self): ...
    def _onRefreshClicked(self): ...
